// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABlhUQkhBepLyH_scM_sbdM22Q9D6jny4',
    appId: '1:437244738404:web:4000634e12f9e439e2d871',
    messagingSenderId: '437244738404',
    projectId: 'practica2-1637c',
    authDomain: 'practica2-1637c.firebaseapp.com',
    storageBucket: 'practica2-1637c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPEJJpOXD_or5JBbszBr6jAo_fGTQSjo',
    appId: '1:437244738404:android:a84c4fbbb3f68f30e2d871',
    messagingSenderId: '437244738404',
    projectId: 'practica2-1637c',
    storageBucket: 'practica2-1637c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1zaBFFwX6AyiP0egAsLuIwdOxTssB6f4',
    appId: '1:437244738404:ios:ac2db0f10be6857be2d871',
    messagingSenderId: '437244738404',
    projectId: 'practica2-1637c',
    storageBucket: 'practica2-1637c.firebasestorage.app',
    iosBundleId: 'com.example.storeplant2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1zaBFFwX6AyiP0egAsLuIwdOxTssB6f4',
    appId: '1:437244738404:ios:ac2db0f10be6857be2d871',
    messagingSenderId: '437244738404',
    projectId: 'practica2-1637c',
    storageBucket: 'practica2-1637c.firebasestorage.app',
    iosBundleId: 'com.example.storeplant2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABlhUQkhBepLyH_scM_sbdM22Q9D6jny4',
    appId: '1:437244738404:web:f91dc09a02e2008ce2d871',
    messagingSenderId: '437244738404',
    projectId: 'practica2-1637c',
    authDomain: 'practica2-1637c.firebaseapp.com',
    storageBucket: 'practica2-1637c.firebasestorage.app',
  );
}
